from typing import Protocol


class AppCoordinatorProtocol(Protocol):
    def start_app(self) -> None: ...

    def open_create_report_window(self) -> None: ...

    def open_create_protocol_window(self) -> None: ...

    def close_app(self) -> None: ...


class ReportCoordinatorProtocol(Protocol):
    def open_report_window(self) -> None: ...
