from typing import Protocol

from src.gui.interfaces.views import ReportsWindowProtocol


class AppCoordinatorProtocol(Protocol):
    def start_app(self) -> None: ...

    def open_main_menu_window(self) -> None: ...

    def open_reports_window(self) -> None: ...

    def open_protocols_window(self) -> None: ...


class ReportsCoordinatorProtocol(Protocol):
    def start_session(self) -> None: ...

    @property
    def reports_window(self) -> ReportsWindowProtocol: ...

    def open_main_menu_window(self) -> None: ...

    def open_divisions_view(self) -> None: ...

    def open_staff_view(self) -> None: ...

    def open_work_types_view(self) -> None: ...

    def open_works_view(self) -> None: ...

    def open_orders_view(self) -> None: ...

    def open_work_events_view(self) -> None: ...


class ProtocolsCoordinatorProtocol(Protocol):
    def start_protocol_session(self) -> None: ...

    def open_main_menu_window(self) -> None: ...
